columnSuffix: null
contentColumnType: string
fieldGroup: ed4f4722-db0d-4f33-ac6c-827e244388d7 # Common
handle: blocks
instructions: null
name: Blocks
searchable: false
settings:
  maxBlocks: null
  maxLevels: null
  maxTopBlocks: null
  minBlocks: null
  minLevels: null
  minTopBlocks: null
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: benf\neo\Field
