columnSuffix: null
contentColumnType: string
fieldGroup: ed4f4722-db0d-4f33-ac6c-827e244388d7 # Common
handle: images
instructions: null
name: Images
searchable: false
settings:
  allowSelfRelations: false
  allowSubfolders: false
  allowUploads: true
  allowedKinds:
    - image
    - video
  defaultUploadLocationSource: 'volume:f3d4e367-d7dd-459c-a9de-11dd87a70cdc' # Images
  defaultUploadLocationSubpath: null
  localizeRelations: false
  maxRelations: 4
  minRelations: null
  previewMode: full
  restrictFiles: true
  restrictLocation: false
  restrictedDefaultUploadSubpath: null
  restrictedLocationSource: 'volume:f3d4e367-d7dd-459c-a9de-11dd87a70cdc' # Images
  restrictedLocationSubpath: null
  selectionCondition:
    __assoc__:
      -
        - elementType
        - craft\elements\Asset
      -
        - fieldContext
        - global
      -
        - class
        - craft\elements\conditions\assets\AssetCondition
  selectionLabel: null
  showSiteMenu: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  source: null
  sources:
    - 'volume:f3d4e367-d7dd-459c-a9de-11dd87a70cdc' # Images
    - 'volume:a0d82af4-339f-430f-9bb8-f2f455642252' # Videos
  targetSiteId: null
  validateRelatedElements: false
  viewMode: list
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
