fieldLayouts:
  1cb37dc9-26a0-4bd4-9e1f-df8e6bc628fd:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 2e99207f-4f2f-4767-8b78-858b08852796
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: e5fb7200-8192-4c3a-b270-625e56a1197d # Logo
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: bcf0b3ac-2c69-46c9-822e-eba74ec851ed
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 62200b20-36fe-447f-aaec-97df6bb416a1 # Website
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: aeb96f92-85e7-48a5-b61d-47d29959dc48
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 72af97a4-c296-4a18-9d4d-b44995e542e3
        userCondition: null
handle: default
hasTitleField: true
name: Default
section: 249aace2-bd89-4989-b2b3-504ad6214021 # Clients
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
