childBlocks: null
conditions: null
description: ''
enabled: true
field: 937f08fb-c57a-4702-a099-98dd7db74e7f # Blocks
fieldLayouts:
  bd893402-85a8-4bc6-912f-bac523ccec4d:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: d64dba0e-b3dd-4726-a5f3-d77f911363a9 # Block ID
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5806ebc0-614f-4c4a-be64-14c1cc73c309
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 9b85cb2e-64d9-43b5-8693-68097a618895 # Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8fe80afb-6e40-4b1c-81c6-ecff76d666da
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: ad2057fb-7a69-4edc-add1-60ca888e8e08 # Body
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f8f5ddcf-9370-4a75-950e-59c73ab20f6b
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 0c266d91-65b0-4f15-9240-f99b8fab3428
        userCondition: null
group: null
groupChildBlockTypes: true
handle: textBlock
icon: null
ignorePermissions: true
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
minBlocks: 0
minChildBlocks: 0
minSiblingBlocks: 0
name: Text
sortOrder: 1
topLevel: true
